### ISSUE TITLE
Wrong ao5 calculation when there's a DNF/When there are less than 5 solves

### ISSUE THREAD

**Issue by Iurig** [coder13/LetsCube#54] opened 2020-04-26 01:17 UTC
Exactly as explained, here's the relevant screenshots:
![image](https://user-images.githubusercontent.com/45807541/80294739-0a61e300-8742-11ea-9268-c7daa9c507d3.png)

![image](https://user-images.githubusercontent.com/45807541/80294768-439a5300-8742-11ea-91d9-847db36c9395.png)

Screenshots taken from firefox on windows.

**Comment by coder13** [comment] 2020-04-26 02:27
This appears to be an error in caching. 
You're missing a few updates. Press ctrl+shift+r to update.
You should also have best stats listed but don't because you don't have that code.

**Comment by coder13** [comment] 2020-04-26 19:50
Closing until I can reproduce with current code.

**Closed** 2020-04-26 19:50 UTC
Labels: bug, good first issue
